/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soda-cans-4e0be610db9646929d8be84491f1a72f
Title: Soda Cans
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    ["Can001_03_-_Default_0"]: THREE.Mesh;
    ["Can001_02_-_Default_0"]: THREE.Mesh;
    ["Can003_08_-_Default_0"]: THREE.Mesh;
    ["Can003_02_-_Default_0"]: THREE.Mesh;
  };
  materials: {
    ["02_-_Default"]: THREE.MeshStandardMaterial;
    ["03_-_Default"]: THREE.MeshStandardMaterial;
    ["08_-_Default"]: THREE.MeshStandardMaterial;
  };
};

const Cans = forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
  (props, ref) => {
    const { nodes, materials } = useGLTF("/model/soda_cans.glb") as GLTFResult;
    return (
      <group {...props} ref={ref}>
        <group
          position={[-80.537, 0, 0.242]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.819, 0.819, 1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Can001_03_-_Default_0"].geometry}
            material={materials["03_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Can001_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
        </group>

        <group
          position={[160.983, 0, 0.242]}
          rotation={[-Math.PI / 2, 0, Math.PI / 4]}
          scale={[0.819, 0.819, 1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Can003_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Can003_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
        </group>
      </group>
    );
  }
);

useGLTF.preload("/model/soda_cans.glb");
export default Cans;
